### PR TITLE
Threw up a landing page. Messily integrated with rest of front-end.

### PR DESCRIPTION
**Pull request by tarifhaque**
Clean up, ASAP!

### CODE REVIEW

**Comment by Taitrnator** [comment]
looks good! just need to work these styles into sass so they don't get stepped on /step on other styles. Need to decide whats a specific style and what should be a site style.

**Comment by Taitrnator** [comment]
moved some things around. Design looks good but switched railway to header font and made kreon the serif font. Also removed some button styles and media queries since the general stuff will need to be changed in the foundation settings files 

whats left for this issue is content on that page

**Comment by tarifhaque** [comment]
Excellent. But not seeing commits associated with changes. Have you pushed your commits to remote? I did merge datavis branch with gh-pages branch yesterday, so all changes we make should be live.

**Comment by Taitrnator** [comment]
derp, tried to push to wrong branch, should see them now

**Comment by agrueneberg** [comment]
Very nice, I like it!

**Pull request merged**
